# Generated by Django 2.1.3 on 2018-11-21 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cups',
            new_name='Cup',
        ),
        migrations.RenameModel(
            old_name='Fixtures',
            new_name='Fixture',
        ),
        migrations.RenameModel(
            old_name='FixturePlayers',
            new_name='FixturePlayer',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
    ]
