# Generated by Django 2.1.3 on 2018-11-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupapp', '0002_auto_20181121_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='cup',
            name='away_slots',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cup',
            name='home_slots',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_goals',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_goals',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
